config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :books do
    resources :comments
    collection do
      get 'search'
    end
  end
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    # @book.comments
    validates :title, presence: true, length: { minimum: 3, message: 'Too short to post!' }
    validates :description, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
  belongs_to :user, foreign_key: :user_id
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :books
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format:{ with: VALID_EMAIL_REGEX },
                    uniqueness: true

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        # descで新しい順に並び替える
        @books = Book.all.order(created_at: 'desc')
    end

    def show
        @book = Book.find(params[:id])
    end

    def new
        @book = Book.new(title: params[:title])
    end

    def create
        @book = Book.new(book_params)
        if @book.save
            # redirect
            redirect_to books_path
        else
            render 'new'
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            redirect_to books_path
        else
            render 'edit'
        end
    end

    require 'net/https'
    require 'json'
    require 'uri'

    def search
        if params[:title]
            uri = URI.parse("https://www.googleapis.com/books/v1/volumes?q=#{URI.encode_www_form_component(params[:title])}")
            http = Net::HTTP.new(uri.host, uri.port)
            http.use_ssl = true
            response = http.get(uri.request_uri)
            @result = JSON.parse(response.body)
        end
    end
    

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    private
        def book_params
            params.require(:book).permit(:title, :description)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @book = Book.find(params[:book_id])
        @book.comments.create(comment_params)
        redirect_to user_book_path(@book)
    end

    def destroy
        @book = Book.find(params[:book_id])
        @comment = @book.comments.find(params[:id])
        @comment.destroy
        redirect_to user_book_path(@book)
    end

    private
        def comment_params
            params.require(:comment).permit(:description, :pages)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
    else
      # エラーメッセージを作成する
      flash.now[:danger] = 'Invalid email/password combination'
    render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            reset_session
            log_in @user
            flash[:success] = "Welcome to the Sample App!"
            redirect_to @user
        else
            render 'new', status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # 渡されたユーザーでログインする
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    # ユーザーがログインしていればtrue、その他ならfalseを返す
    def logged_in?
        !current_user.nil?
    end

    # 現在のユーザーをログアウトする
    def log_out
        reset_session
        @current_user = nil   # 安全のため
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
<p>
    <%= f.text_field :title, placeholder: 'enter title' %>
    <% if @book.errors.messages[:title].any? %>
    <span class="error"><%= @book.errors.messages[:title][0] %></span>
    <% end %>
</p>
<p>
    <%= f.text_area :description, placeholder: 'enter body text' %>
    <% if @book.errors.messages[:description].any? %>
    <span class="error"><%= @book.errors.messages[:description][0] %></span>
    <% end %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Page</h1>
<%= @book.title %>

<%= form_with(model: [@user, @book], url: user_book_path) do |f| %>
<p>
    <%= f.text_area :description, placeholder: 'enter body text' %>
    <% if @book.errors.messages[:description].any? %>
    <span class="error"><%= @book.errors.messages[:description][0] %></span>
    <% end %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/books/index.html.erb
<h1>Reading Management</h1>
<%= link_to 'Add New', search_user_books_path, class: 'header-menu' %>
<ul>
<% @books.each do |book| %>
<li><%= link_to book.title, user_book_path(user_id: params[:user_id], id: book.id) %>
<%= link_to '[edit]', edit_user_book_path(user_id: params[:user_id], id: book.id), class: 'command' %>
<%= link_to "delete", user_book_path(user_id: params[:user_id], id: book.id), 
data: { turbo_method: :delete, turbo_confirm: 'Sure?'}%>
</li>
<% end %>
</ul>

app/views/books/new.html.erb
<h1>Add New Page</h1>
<%= form_with(model: [@user, @book], url: user_books_path,remote: false ) do |form| %>
<%= form.label :title %>
<%= form.text_field :title, id: 'book_title' , value: params[:title]%>

<%= form.text_area :description, placeholder: 'enter body text' %>
<% if @book.errors.messages[:description].any? %>
    <span class="error"><%= @book.errors.messages[:description][0] %></span>
<% end %>
<%= form.submit %>
<% end %>

app/views/books/search.html.erb
<%= form_tag search_books_path, method: :get, remote: true do %>
    <%= text_field_tag :title, params[:title], placeholder: "Enter book title" %>
    <%= submit_tag "Search" %>
<% end %>

<% if @result.present? %>
    <% if @result['items'].present? %>
        <% @result['items'].each do |item| %>
        <div class="search-result">
                <%= link_to item['volumeInfo']['title'], new_book_path(title: item['volumeInfo']['title']) %>
        </div>
        <% end %>
    <% else %>
        <div class="search-result">
            <script>
                alert("Please enter a book title.");
            </script>
        </div>
    <% end %>
<% end %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<p><%= simple_format @book.description %></p>


<h3>Comments</h3>
<% if @book.comments.any? %>
<ul>
<% @book.comments.each do |comment| %>
<li>
    <%= comment.description %>
    P<%= comment.pages %>
    <%= link_to "delete", user_book_comment_path(@book, comment), 
    data: { turbo_method: :delete, turbo_confirm: 'Sure?'}%>
</li>
<% end %>
</ul>
<% end %>
<%= form_with(moddel: [@book, @book.comments.build]) do |f| %>

<p>
    <%= f.text_field :description, placeholder: 'コメントを入力'%>
</p>
<p>
    <%= f.number_field :pages, placeholder: 'ページ数を入力'%>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%= link_to "sample app", root_path, id: "logo" %>
<nav>
    <ul class="nav navbar-nav navbar-right">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Help", help_path %></li>
    <% if logged_in? %>
        <li><%= link_to "Users", '#' %></li>
        <li class="dropdown">
        <a href="#" id="account" class="dropdown-toggle">
            Account <b class="caret"></b>
        </a>
        <ul id="dropdown-menu" class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
            <%= link_to "Log out", logout_path,
                                    data: { "turbo-method": :delete } %>
            </li>
        </ul>
        </li>
    <% else %>
        <li><%= link_to "Log in", login_path %></li>
    <% end %>
    </ul>
</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadingManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= link_to 'HOME', root_path,class: 'backhome' %>
  <div class="container">
  
  <%=yield%>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= gravatar_for @user %><%= @user.name %></h1>

<%= link_to 'Books Page', user_books_path(@user, @books)%>